name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fe-tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      # - name: Parse coverage report
      #   id: parse-coverage
      #   run: echo "::set-output name=coverage-summary::$(cat coverage/summary.json)"

      # - name: Create GitHub comment
      # TODO: Write a script to parse the coverage report and create a comment on the PR
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const summary = JSON.parse(process.env.coverage_summary);
      #       const message = `Code Coverage Summary:\n\nCoverage Percentage: ${summary.coveragePercentage}%\nLines Covered: ${summary.linesCovered}\nLines Total: ${summary.linesTotal}`;

      #       github.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #         body: message
      #       });
